version: "2.4"
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  jaeger:
    image: jaegertracing/all-in-one:1.22
    mem_limit: 512M
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
