// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.2
// source: all.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisibilityUpdate_Action int32

const (
	VisibilityUpdate_ADD    VisibilityUpdate_Action = 0
	VisibilityUpdate_REMOVE VisibilityUpdate_Action = 1
)

// Enum value maps for VisibilityUpdate_Action.
var (
	VisibilityUpdate_Action_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	VisibilityUpdate_Action_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x VisibilityUpdate_Action) Enum() *VisibilityUpdate_Action {
	p := new(VisibilityUpdate_Action)
	*p = x
	return p
}

func (x VisibilityUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_all_proto_enumTypes[0].Descriptor()
}

func (VisibilityUpdate_Action) Type() protoreflect.EnumType {
	return &file_all_proto_enumTypes[0]
}

func (x VisibilityUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityUpdate_Action.Descriptor instead.
func (VisibilityUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{2, 0}
}

type TickUpdatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TickUpdatesReq) Reset() {
	*x = TickUpdatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickUpdatesReq) ProtoMessage() {}

func (x *TickUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickUpdatesReq.ProtoReflect.Descriptor instead.
func (*TickUpdatesReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{0}
}

type TickUpdatesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisibilityUpdates []*VisibilityUpdate `protobuf:"bytes,1,rep,name=visibilityUpdates,proto3" json:"visibilityUpdates,omitempty"`
}

func (x *TickUpdatesRes) Reset() {
	*x = TickUpdatesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickUpdatesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickUpdatesRes) ProtoMessage() {}

func (x *TickUpdatesRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickUpdatesRes.ProtoReflect.Descriptor instead.
func (*TickUpdatesRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{1}
}

func (x *TickUpdatesRes) GetVisibilityUpdates() []*VisibilityUpdate {
	if x != nil {
		return x.VisibilityUpdates
	}
	return nil
}

type VisibilityUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Renderable *Renderable             `protobuf:"bytes,1,opt,name=renderable,proto3" json:"renderable,omitempty"`
	Action     VisibilityUpdate_Action `protobuf:"varint,2,opt,name=action,proto3,enum=grpc.VisibilityUpdate_Action" json:"action,omitempty"`
	Tick       int64                   `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
}

func (x *VisibilityUpdate) Reset() {
	*x = VisibilityUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisibilityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityUpdate) ProtoMessage() {}

func (x *VisibilityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityUpdate.ProtoReflect.Descriptor instead.
func (*VisibilityUpdate) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{2}
}

func (x *VisibilityUpdate) GetRenderable() *Renderable {
	if x != nil {
		return x.Renderable
	}
	return nil
}

func (x *VisibilityUpdate) GetAction() VisibilityUpdate_Action {
	if x != nil {
		return x.Action
	}
	return VisibilityUpdate_ADD
}

func (x *VisibilityUpdate) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type ChatUpdatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatUpdatesReq) Reset() {
	*x = ChatUpdatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdatesReq) ProtoMessage() {}

func (x *ChatUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdatesReq.ProtoReflect.Descriptor instead.
func (*ChatUpdatesReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{3}
}

type ChatUpdatesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatUpdatesRes) Reset() {
	*x = ChatUpdatesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUpdatesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdatesRes) ProtoMessage() {}

func (x *ChatUpdatesRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdatesRes.ProtoReflect.Descriptor instead.
func (*ChatUpdatesRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{4}
}

func (x *ChatUpdatesRes) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type MoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{5}
}

type MoveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveRes) Reset() {
	*x = MoveRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRes) ProtoMessage() {}

func (x *MoveRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRes.ProtoReflect.Descriptor instead.
func (*MoveRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{6}
}

type ReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *ReadReq) Reset() {
	*x = ReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReq) ProtoMessage() {}

func (x *ReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReq.ProtoReflect.Descriptor instead.
func (*ReadReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{7}
}

func (x *ReadReq) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type ReadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadRes) Reset() {
	*x = ReadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRes) ProtoMessage() {}

func (x *ReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRes.ProtoReflect.Descriptor instead.
func (*ReadRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{8}
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{9}
}

func (x *JoinReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId         int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TickMilliseconds int32 `protobuf:"varint,2,opt,name=tickMilliseconds,proto3" json:"tickMilliseconds,omitempty"`
}

func (x *JoinRes) Reset() {
	*x = JoinRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRes) ProtoMessage() {}

func (x *JoinRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRes.ProtoReflect.Descriptor instead.
func (*JoinRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinRes) GetTickMilliseconds() int32 {
	if x != nil {
		return x.TickMilliseconds
	}
	return 0
}

type SayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SayReq) Reset() {
	*x = SayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayReq) ProtoMessage() {}

func (x *SayReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayReq.ProtoReflect.Descriptor instead.
func (*SayReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{11}
}

func (x *SayReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SayRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayRes) Reset() {
	*x = SayRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRes) ProtoMessage() {}

func (x *SayRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRes.ProtoReflect.Descriptor instead.
func (*SayRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{12}
}

type Renderable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity *Velocity `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Char     string    `protobuf:"bytes,4,opt,name=char,proto3" json:"char,omitempty"`
	Color    uint32    `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Renderable) Reset() {
	*x = Renderable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Renderable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renderable) ProtoMessage() {}

func (x *Renderable) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renderable.ProtoReflect.Descriptor instead.
func (*Renderable) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{13}
}

func (x *Renderable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Renderable) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Renderable) GetVelocity() *Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Renderable) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

func (x *Renderable) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{15}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Velocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Velocity) Reset() {
	*x = Velocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Velocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Velocity) ProtoMessage() {}

func (x *Velocity) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Velocity.ProtoReflect.Descriptor instead.
func (*Velocity) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{16}
}

func (x *Velocity) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Velocity) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_all_proto protoreflect.FileDescriptor

var file_all_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x56, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x10,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x30, 0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x22, 0x1d, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x22, 0x10, 0x0a, 0x0e,
	0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3d,
	0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x09, 0x0a,
	0x07, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22, 0x09, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2a,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10,
	0x74, 0x69, 0x63, 0x6b, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x4d, 0x69, 0x6c, 0x6c,
	0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x08, 0x0a, 0x06, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x08, 0x76,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x52, 0x08, 0x76,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x22, 0x35, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79,
	0x22, 0x26, 0x0a, 0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x32, 0xaa, 0x02, 0x0a, 0x05, 0x45, 0x73, 0x69,
	0x76, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x3d, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x2e, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x26, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12,
	0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x26, 0x0a,
	0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x65, 0x73,
	0x69, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_proto_rawDescOnce sync.Once
	file_all_proto_rawDescData = file_all_proto_rawDesc
)

func file_all_proto_rawDescGZIP() []byte {
	file_all_proto_rawDescOnce.Do(func() {
		file_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_proto_rawDescData)
	})
	return file_all_proto_rawDescData
}

var file_all_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_all_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_all_proto_goTypes = []interface{}{
	(VisibilityUpdate_Action)(0), // 0: grpc.VisibilityUpdate.Action
	(*TickUpdatesReq)(nil),       // 1: grpc.TickUpdatesReq
	(*TickUpdatesRes)(nil),       // 2: grpc.TickUpdatesRes
	(*VisibilityUpdate)(nil),     // 3: grpc.VisibilityUpdate
	(*ChatUpdatesReq)(nil),       // 4: grpc.ChatUpdatesReq
	(*ChatUpdatesRes)(nil),       // 5: grpc.ChatUpdatesRes
	(*MoveReq)(nil),              // 6: grpc.MoveReq
	(*MoveRes)(nil),              // 7: grpc.MoveRes
	(*ReadReq)(nil),              // 8: grpc.ReadReq
	(*ReadRes)(nil),              // 9: grpc.ReadRes
	(*JoinReq)(nil),              // 10: grpc.JoinReq
	(*JoinRes)(nil),              // 11: grpc.JoinRes
	(*SayReq)(nil),               // 12: grpc.SayReq
	(*SayRes)(nil),               // 13: grpc.SayRes
	(*Renderable)(nil),           // 14: grpc.Renderable
	(*ChatMessage)(nil),          // 15: grpc.ChatMessage
	(*Position)(nil),             // 16: grpc.Position
	(*Velocity)(nil),             // 17: grpc.Velocity
}
var file_all_proto_depIdxs = []int32{
	3,  // 0: grpc.TickUpdatesRes.visibilityUpdates:type_name -> grpc.VisibilityUpdate
	14, // 1: grpc.VisibilityUpdate.renderable:type_name -> grpc.Renderable
	0,  // 2: grpc.VisibilityUpdate.action:type_name -> grpc.VisibilityUpdate.Action
	15, // 3: grpc.ChatUpdatesRes.message:type_name -> grpc.ChatMessage
	16, // 4: grpc.ReadReq.position:type_name -> grpc.Position
	16, // 5: grpc.Renderable.position:type_name -> grpc.Position
	17, // 6: grpc.Renderable.velocity:type_name -> grpc.Velocity
	1,  // 7: grpc.Esive.TickUpdates:input_type -> grpc.TickUpdatesReq
	4,  // 8: grpc.Esive.ChatUpdates:input_type -> grpc.ChatUpdatesReq
	17, // 9: grpc.Esive.SetVelocity:input_type -> grpc.Velocity
	8,  // 10: grpc.Esive.Read:input_type -> grpc.ReadReq
	12, // 11: grpc.Esive.Say:input_type -> grpc.SayReq
	10, // 12: grpc.Esive.Join:input_type -> grpc.JoinReq
	2,  // 13: grpc.Esive.TickUpdates:output_type -> grpc.TickUpdatesRes
	5,  // 14: grpc.Esive.ChatUpdates:output_type -> grpc.ChatUpdatesRes
	7,  // 15: grpc.Esive.SetVelocity:output_type -> grpc.MoveRes
	9,  // 16: grpc.Esive.Read:output_type -> grpc.ReadRes
	13, // 17: grpc.Esive.Say:output_type -> grpc.SayRes
	11, // 18: grpc.Esive.Join:output_type -> grpc.JoinRes
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_all_proto_init() }
func file_all_proto_init() {
	if File_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickUpdatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickUpdatesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisibilityUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatUpdatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatUpdatesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Renderable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Velocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_all_proto_goTypes,
		DependencyIndexes: file_all_proto_depIdxs,
		EnumInfos:         file_all_proto_enumTypes,
		MessageInfos:      file_all_proto_msgTypes,
	}.Build()
	File_all_proto = out.File
	file_all_proto_rawDesc = nil
	file_all_proto_goTypes = nil
	file_all_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EsiveClient is the client API for Esive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EsiveClient interface {
	TickUpdates(ctx context.Context, in *TickUpdatesReq, opts ...grpc.CallOption) (Esive_TickUpdatesClient, error)
	ChatUpdates(ctx context.Context, in *ChatUpdatesReq, opts ...grpc.CallOption) (Esive_ChatUpdatesClient, error)
	SetVelocity(ctx context.Context, in *Velocity, opts ...grpc.CallOption) (*MoveRes, error)
	Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadRes, error)
	Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayRes, error)
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRes, error)
}

type esiveClient struct {
	cc grpc.ClientConnInterface
}

func NewEsiveClient(cc grpc.ClientConnInterface) EsiveClient {
	return &esiveClient{cc}
}

func (c *esiveClient) TickUpdates(ctx context.Context, in *TickUpdatesReq, opts ...grpc.CallOption) (Esive_TickUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Esive_serviceDesc.Streams[0], "/grpc.Esive/TickUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &esiveTickUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Esive_TickUpdatesClient interface {
	Recv() (*TickUpdatesRes, error)
	grpc.ClientStream
}

type esiveTickUpdatesClient struct {
	grpc.ClientStream
}

func (x *esiveTickUpdatesClient) Recv() (*TickUpdatesRes, error) {
	m := new(TickUpdatesRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *esiveClient) ChatUpdates(ctx context.Context, in *ChatUpdatesReq, opts ...grpc.CallOption) (Esive_ChatUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Esive_serviceDesc.Streams[1], "/grpc.Esive/ChatUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &esiveChatUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Esive_ChatUpdatesClient interface {
	Recv() (*ChatUpdatesRes, error)
	grpc.ClientStream
}

type esiveChatUpdatesClient struct {
	grpc.ClientStream
}

func (x *esiveChatUpdatesClient) Recv() (*ChatUpdatesRes, error) {
	m := new(ChatUpdatesRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *esiveClient) SetVelocity(ctx context.Context, in *Velocity, opts ...grpc.CallOption) (*MoveRes, error) {
	out := new(MoveRes)
	err := c.cc.Invoke(ctx, "/grpc.Esive/SetVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esiveClient) Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadRes, error) {
	out := new(ReadRes)
	err := c.cc.Invoke(ctx, "/grpc.Esive/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esiveClient) Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayRes, error) {
	out := new(SayRes)
	err := c.cc.Invoke(ctx, "/grpc.Esive/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esiveClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRes, error) {
	out := new(JoinRes)
	err := c.cc.Invoke(ctx, "/grpc.Esive/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EsiveServer is the server API for Esive service.
type EsiveServer interface {
	TickUpdates(*TickUpdatesReq, Esive_TickUpdatesServer) error
	ChatUpdates(*ChatUpdatesReq, Esive_ChatUpdatesServer) error
	SetVelocity(context.Context, *Velocity) (*MoveRes, error)
	Read(context.Context, *ReadReq) (*ReadRes, error)
	Say(context.Context, *SayReq) (*SayRes, error)
	Join(context.Context, *JoinReq) (*JoinRes, error)
}

// UnimplementedEsiveServer can be embedded to have forward compatible implementations.
type UnimplementedEsiveServer struct {
}

func (*UnimplementedEsiveServer) TickUpdates(*TickUpdatesReq, Esive_TickUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method TickUpdates not implemented")
}
func (*UnimplementedEsiveServer) ChatUpdates(*ChatUpdatesReq, Esive_ChatUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatUpdates not implemented")
}
func (*UnimplementedEsiveServer) SetVelocity(context.Context, *Velocity) (*MoveRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVelocity not implemented")
}
func (*UnimplementedEsiveServer) Read(context.Context, *ReadReq) (*ReadRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedEsiveServer) Say(context.Context, *SayReq) (*SayRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedEsiveServer) Join(context.Context, *JoinReq) (*JoinRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterEsiveServer(s *grpc.Server, srv EsiveServer) {
	s.RegisterService(&_Esive_serviceDesc, srv)
}

func _Esive_TickUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TickUpdatesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EsiveServer).TickUpdates(m, &esiveTickUpdatesServer{stream})
}

type Esive_TickUpdatesServer interface {
	Send(*TickUpdatesRes) error
	grpc.ServerStream
}

type esiveTickUpdatesServer struct {
	grpc.ServerStream
}

func (x *esiveTickUpdatesServer) Send(m *TickUpdatesRes) error {
	return x.ServerStream.SendMsg(m)
}

func _Esive_ChatUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatUpdatesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EsiveServer).ChatUpdates(m, &esiveChatUpdatesServer{stream})
}

type Esive_ChatUpdatesServer interface {
	Send(*ChatUpdatesRes) error
	grpc.ServerStream
}

type esiveChatUpdatesServer struct {
	grpc.ServerStream
}

func (x *esiveChatUpdatesServer) Send(m *ChatUpdatesRes) error {
	return x.ServerStream.SendMsg(m)
}

func _Esive_SetVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Velocity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsiveServer).SetVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Esive/SetVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsiveServer).SetVelocity(ctx, req.(*Velocity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Esive_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsiveServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Esive/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsiveServer).Read(ctx, req.(*ReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Esive_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsiveServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Esive/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsiveServer).Say(ctx, req.(*SayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Esive_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsiveServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Esive/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsiveServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Esive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Esive",
	HandlerType: (*EsiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVelocity",
			Handler:    _Esive_SetVelocity_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Esive_Read_Handler,
		},
		{
			MethodName: "Say",
			Handler:    _Esive_Say_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Esive_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TickUpdates",
			Handler:       _Esive_TickUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatUpdates",
			Handler:       _Esive_ChatUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "all.proto",
}
