name: release

on:
  pull_request:
  push:

jobs:
  goreleaser:
    name: Run goreleaser
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push server to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/code-cell/esive_server:latest,ghcr.io/code-cell/esive_server:${GITHUB_REF}
          file: Dockerfile.server

      - name: Push client to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/code-cell/esive_client:latest,ghcr.io/code-cell/esive_client:${GITHUB_REF}
          file: Dockerfile.client
