// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: all.proto

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisibilityUpdatesRes_Action int32

const (
	VisibilityUpdatesRes_ADD    VisibilityUpdatesRes_Action = 0
	VisibilityUpdatesRes_REMOVE VisibilityUpdatesRes_Action = 1
)

// Enum value maps for VisibilityUpdatesRes_Action.
var (
	VisibilityUpdatesRes_Action_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	VisibilityUpdatesRes_Action_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x VisibilityUpdatesRes_Action) Enum() *VisibilityUpdatesRes_Action {
	p := new(VisibilityUpdatesRes_Action)
	*p = x
	return p
}

func (x VisibilityUpdatesRes_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityUpdatesRes_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_all_proto_enumTypes[0].Descriptor()
}

func (VisibilityUpdatesRes_Action) Type() protoreflect.EnumType {
	return &file_all_proto_enumTypes[0]
}

func (x VisibilityUpdatesRes_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityUpdatesRes_Action.Descriptor instead.
func (VisibilityUpdatesRes_Action) EnumDescriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{1, 0}
}

type VisibilityUpdatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VisibilityUpdatesReq) Reset() {
	*x = VisibilityUpdatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisibilityUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityUpdatesReq) ProtoMessage() {}

func (x *VisibilityUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityUpdatesReq.ProtoReflect.Descriptor instead.
func (*VisibilityUpdatesReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{0}
}

type VisibilityUpdatesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Renderable *Renderable                 `protobuf:"bytes,1,opt,name=renderable,proto3" json:"renderable,omitempty"`
	Action     VisibilityUpdatesRes_Action `protobuf:"varint,2,opt,name=action,proto3,enum=models.VisibilityUpdatesRes_Action" json:"action,omitempty"`
}

func (x *VisibilityUpdatesRes) Reset() {
	*x = VisibilityUpdatesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisibilityUpdatesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityUpdatesRes) ProtoMessage() {}

func (x *VisibilityUpdatesRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityUpdatesRes.ProtoReflect.Descriptor instead.
func (*VisibilityUpdatesRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{1}
}

func (x *VisibilityUpdatesRes) GetRenderable() *Renderable {
	if x != nil {
		return x.Renderable
	}
	return nil
}

func (x *VisibilityUpdatesRes) GetAction() VisibilityUpdatesRes_Action {
	if x != nil {
		return x.Action
	}
	return VisibilityUpdatesRes_ADD
}

type ChatUpdatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatUpdatesReq) Reset() {
	*x = ChatUpdatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdatesReq) ProtoMessage() {}

func (x *ChatUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdatesReq.ProtoReflect.Descriptor instead.
func (*ChatUpdatesReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{2}
}

type ChatUpdatesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatUpdatesRes) Reset() {
	*x = ChatUpdatesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUpdatesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdatesRes) ProtoMessage() {}

func (x *ChatUpdatesRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdatesRes.ProtoReflect.Descriptor instead.
func (*ChatUpdatesRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{3}
}

func (x *ChatUpdatesRes) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type MoveUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveUpReq) Reset() {
	*x = MoveUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveUpReq) ProtoMessage() {}

func (x *MoveUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveUpReq.ProtoReflect.Descriptor instead.
func (*MoveUpReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{4}
}

type MoveUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *MoveUpRes) Reset() {
	*x = MoveUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveUpRes) ProtoMessage() {}

func (x *MoveUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveUpRes.ProtoReflect.Descriptor instead.
func (*MoveUpRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{5}
}

func (x *MoveUpRes) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type MoveDownReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveDownReq) Reset() {
	*x = MoveDownReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDownReq) ProtoMessage() {}

func (x *MoveDownReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDownReq.ProtoReflect.Descriptor instead.
func (*MoveDownReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{6}
}

type MoveDownRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *MoveDownRes) Reset() {
	*x = MoveDownRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDownRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDownRes) ProtoMessage() {}

func (x *MoveDownRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDownRes.ProtoReflect.Descriptor instead.
func (*MoveDownRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{7}
}

func (x *MoveDownRes) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type MoveLeftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveLeftReq) Reset() {
	*x = MoveLeftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveLeftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveLeftReq) ProtoMessage() {}

func (x *MoveLeftReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveLeftReq.ProtoReflect.Descriptor instead.
func (*MoveLeftReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{8}
}

type MoveLeftRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *MoveLeftRes) Reset() {
	*x = MoveLeftRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveLeftRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveLeftRes) ProtoMessage() {}

func (x *MoveLeftRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveLeftRes.ProtoReflect.Descriptor instead.
func (*MoveLeftRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{9}
}

func (x *MoveLeftRes) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type MoveRightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveRightReq) Reset() {
	*x = MoveRightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRightReq) ProtoMessage() {}

func (x *MoveRightReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRightReq.ProtoReflect.Descriptor instead.
func (*MoveRightReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{10}
}

type MoveRightRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *MoveRightRes) Reset() {
	*x = MoveRightRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRightRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRightRes) ProtoMessage() {}

func (x *MoveRightRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRightRes.ProtoReflect.Descriptor instead.
func (*MoveRightRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{11}
}

func (x *MoveRightRes) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type BuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuildReq) Reset() {
	*x = BuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReq) ProtoMessage() {}

func (x *BuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReq.ProtoReflect.Descriptor instead.
func (*BuildReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{12}
}

type BuildRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *BuildRes) Reset() {
	*x = BuildRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRes) ProtoMessage() {}

func (x *BuildRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRes.ProtoReflect.Descriptor instead.
func (*BuildRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{13}
}

func (x *BuildRes) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{14}
}

func (x *JoinReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *JoinRes) Reset() {
	*x = JoinRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRes) ProtoMessage() {}

func (x *JoinRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRes.ProtoReflect.Descriptor instead.
func (*JoinRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{15}
}

func (x *JoinRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SayReq) Reset() {
	*x = SayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayReq) ProtoMessage() {}

func (x *SayReq) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayReq.ProtoReflect.Descriptor instead.
func (*SayReq) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{16}
}

func (x *SayReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SayRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayRes) Reset() {
	*x = SayRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRes) ProtoMessage() {}

func (x *SayRes) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRes.ProtoReflect.Descriptor instead.
func (*SayRes) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{17}
}

type Renderable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Char     string    `protobuf:"bytes,3,opt,name=char,proto3" json:"char,omitempty"`
	Color    int32     `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Renderable) Reset() {
	*x = Renderable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Renderable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renderable) ProtoMessage() {}

func (x *Renderable) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renderable.ProtoReflect.Descriptor instead.
func (*Renderable) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{18}
}

func (x *Renderable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Renderable) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Renderable) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

func (x *Renderable) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{19}
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{20}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_all_proto protoreflect.FileDescriptor

var file_all_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0xa6, 0x01, 0x0a, 0x14,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x72, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f,
	0x56, 0x45, 0x10, 0x01, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65, 0x55,
	0x70, 0x52, 0x65, 0x71, 0x22, 0x39, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x52, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x0d, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x3b,
	0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x4d,
	0x6f, 0x76, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x65, 0x71, 0x22, 0x3b, 0x0a, 0x0b, 0x4d, 0x6f,
	0x76, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x22, 0x3c, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0a, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x22, 0x38, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x07, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x07, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x08, 0x0a, 0x06, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x0a, 0x52, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x22, 0x35, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x32,
	0x83, 0x04, 0x0a, 0x08, 0x49, 0x63, 0x65, 0x63, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06,
	0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x12, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x65,
	0x66, 0x74, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x4c, 0x65, 0x66, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x11, 0x56, 0x69, 0x73, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x41, 0x0a,
	0x0b, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x27, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x04, 0x4a, 0x6f, 0x69,
	0x6e, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x72, 0x6f, 0x63, 0x61, 0x2f, 0x65, 0x63, 0x73, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_proto_rawDescOnce sync.Once
	file_all_proto_rawDescData = file_all_proto_rawDesc
)

func file_all_proto_rawDescGZIP() []byte {
	file_all_proto_rawDescOnce.Do(func() {
		file_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_proto_rawDescData)
	})
	return file_all_proto_rawDescData
}

var file_all_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_all_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_all_proto_goTypes = []interface{}{
	(VisibilityUpdatesRes_Action)(0), // 0: models.VisibilityUpdatesRes.Action
	(*VisibilityUpdatesReq)(nil),     // 1: models.VisibilityUpdatesReq
	(*VisibilityUpdatesRes)(nil),     // 2: models.VisibilityUpdatesRes
	(*ChatUpdatesReq)(nil),           // 3: models.ChatUpdatesReq
	(*ChatUpdatesRes)(nil),           // 4: models.ChatUpdatesRes
	(*MoveUpReq)(nil),                // 5: models.MoveUpReq
	(*MoveUpRes)(nil),                // 6: models.MoveUpRes
	(*MoveDownReq)(nil),              // 7: models.MoveDownReq
	(*MoveDownRes)(nil),              // 8: models.MoveDownRes
	(*MoveLeftReq)(nil),              // 9: models.MoveLeftReq
	(*MoveLeftRes)(nil),              // 10: models.MoveLeftRes
	(*MoveRightReq)(nil),             // 11: models.MoveRightReq
	(*MoveRightRes)(nil),             // 12: models.MoveRightRes
	(*BuildReq)(nil),                 // 13: models.BuildReq
	(*BuildRes)(nil),                 // 14: models.BuildRes
	(*JoinReq)(nil),                  // 15: models.JoinReq
	(*JoinRes)(nil),                  // 16: models.JoinRes
	(*SayReq)(nil),                   // 17: models.SayReq
	(*SayRes)(nil),                   // 18: models.SayRes
	(*Renderable)(nil),               // 19: models.Renderable
	(*ChatMessage)(nil),              // 20: models.ChatMessage
	(*Position)(nil),                 // 21: models.Position
}
var file_all_proto_depIdxs = []int32{
	19, // 0: models.VisibilityUpdatesRes.renderable:type_name -> models.Renderable
	0,  // 1: models.VisibilityUpdatesRes.action:type_name -> models.VisibilityUpdatesRes.Action
	20, // 2: models.ChatUpdatesRes.message:type_name -> models.ChatMessage
	21, // 3: models.MoveUpRes.position:type_name -> models.Position
	21, // 4: models.MoveDownRes.position:type_name -> models.Position
	21, // 5: models.MoveLeftRes.position:type_name -> models.Position
	21, // 6: models.MoveRightRes.position:type_name -> models.Position
	21, // 7: models.BuildRes.position:type_name -> models.Position
	21, // 8: models.Renderable.position:type_name -> models.Position
	5,  // 9: models.Icecream.MoveUp:input_type -> models.MoveUpReq
	7,  // 10: models.Icecream.MoveDown:input_type -> models.MoveDownReq
	9,  // 11: models.Icecream.MoveLeft:input_type -> models.MoveLeftReq
	11, // 12: models.Icecream.MoveRight:input_type -> models.MoveRightReq
	13, // 13: models.Icecream.Build:input_type -> models.BuildReq
	1,  // 14: models.Icecream.VisibilityUpdates:input_type -> models.VisibilityUpdatesReq
	3,  // 15: models.Icecream.ChatUpdates:input_type -> models.ChatUpdatesReq
	17, // 16: models.Icecream.Say:input_type -> models.SayReq
	15, // 17: models.Icecream.Join:input_type -> models.JoinReq
	6,  // 18: models.Icecream.MoveUp:output_type -> models.MoveUpRes
	8,  // 19: models.Icecream.MoveDown:output_type -> models.MoveDownRes
	10, // 20: models.Icecream.MoveLeft:output_type -> models.MoveLeftRes
	12, // 21: models.Icecream.MoveRight:output_type -> models.MoveRightRes
	14, // 22: models.Icecream.Build:output_type -> models.BuildRes
	2,  // 23: models.Icecream.VisibilityUpdates:output_type -> models.VisibilityUpdatesRes
	4,  // 24: models.Icecream.ChatUpdates:output_type -> models.ChatUpdatesRes
	18, // 25: models.Icecream.Say:output_type -> models.SayRes
	16, // 26: models.Icecream.Join:output_type -> models.JoinRes
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_all_proto_init() }
func file_all_proto_init() {
	if File_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisibilityUpdatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisibilityUpdatesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatUpdatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatUpdatesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDownReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDownRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveLeftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveLeftRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRightRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Renderable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_all_proto_goTypes,
		DependencyIndexes: file_all_proto_depIdxs,
		EnumInfos:         file_all_proto_enumTypes,
		MessageInfos:      file_all_proto_msgTypes,
	}.Build()
	File_all_proto = out.File
	file_all_proto_rawDesc = nil
	file_all_proto_goTypes = nil
	file_all_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IcecreamClient is the client API for Icecream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IcecreamClient interface {
	MoveUp(ctx context.Context, in *MoveUpReq, opts ...grpc.CallOption) (*MoveUpRes, error)
	MoveDown(ctx context.Context, in *MoveDownReq, opts ...grpc.CallOption) (*MoveDownRes, error)
	MoveLeft(ctx context.Context, in *MoveLeftReq, opts ...grpc.CallOption) (*MoveLeftRes, error)
	MoveRight(ctx context.Context, in *MoveRightReq, opts ...grpc.CallOption) (*MoveRightRes, error)
	Build(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRes, error)
	VisibilityUpdates(ctx context.Context, in *VisibilityUpdatesReq, opts ...grpc.CallOption) (Icecream_VisibilityUpdatesClient, error)
	ChatUpdates(ctx context.Context, in *ChatUpdatesReq, opts ...grpc.CallOption) (Icecream_ChatUpdatesClient, error)
	Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayRes, error)
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRes, error)
}

type icecreamClient struct {
	cc grpc.ClientConnInterface
}

func NewIcecreamClient(cc grpc.ClientConnInterface) IcecreamClient {
	return &icecreamClient{cc}
}

func (c *icecreamClient) MoveUp(ctx context.Context, in *MoveUpReq, opts ...grpc.CallOption) (*MoveUpRes, error) {
	out := new(MoveUpRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/MoveUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) MoveDown(ctx context.Context, in *MoveDownReq, opts ...grpc.CallOption) (*MoveDownRes, error) {
	out := new(MoveDownRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/MoveDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) MoveLeft(ctx context.Context, in *MoveLeftReq, opts ...grpc.CallOption) (*MoveLeftRes, error) {
	out := new(MoveLeftRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/MoveLeft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) MoveRight(ctx context.Context, in *MoveRightReq, opts ...grpc.CallOption) (*MoveRightRes, error) {
	out := new(MoveRightRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/MoveRight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) Build(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRes, error) {
	out := new(BuildRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) VisibilityUpdates(ctx context.Context, in *VisibilityUpdatesReq, opts ...grpc.CallOption) (Icecream_VisibilityUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Icecream_serviceDesc.Streams[0], "/models.Icecream/VisibilityUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &icecreamVisibilityUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Icecream_VisibilityUpdatesClient interface {
	Recv() (*VisibilityUpdatesRes, error)
	grpc.ClientStream
}

type icecreamVisibilityUpdatesClient struct {
	grpc.ClientStream
}

func (x *icecreamVisibilityUpdatesClient) Recv() (*VisibilityUpdatesRes, error) {
	m := new(VisibilityUpdatesRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *icecreamClient) ChatUpdates(ctx context.Context, in *ChatUpdatesReq, opts ...grpc.CallOption) (Icecream_ChatUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Icecream_serviceDesc.Streams[1], "/models.Icecream/ChatUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &icecreamChatUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Icecream_ChatUpdatesClient interface {
	Recv() (*ChatUpdatesRes, error)
	grpc.ClientStream
}

type icecreamChatUpdatesClient struct {
	grpc.ClientStream
}

func (x *icecreamChatUpdatesClient) Recv() (*ChatUpdatesRes, error) {
	m := new(ChatUpdatesRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *icecreamClient) Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayRes, error) {
	out := new(SayRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icecreamClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRes, error) {
	out := new(JoinRes)
	err := c.cc.Invoke(ctx, "/models.Icecream/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IcecreamServer is the server API for Icecream service.
type IcecreamServer interface {
	MoveUp(context.Context, *MoveUpReq) (*MoveUpRes, error)
	MoveDown(context.Context, *MoveDownReq) (*MoveDownRes, error)
	MoveLeft(context.Context, *MoveLeftReq) (*MoveLeftRes, error)
	MoveRight(context.Context, *MoveRightReq) (*MoveRightRes, error)
	Build(context.Context, *BuildReq) (*BuildRes, error)
	VisibilityUpdates(*VisibilityUpdatesReq, Icecream_VisibilityUpdatesServer) error
	ChatUpdates(*ChatUpdatesReq, Icecream_ChatUpdatesServer) error
	Say(context.Context, *SayReq) (*SayRes, error)
	Join(context.Context, *JoinReq) (*JoinRes, error)
}

// UnimplementedIcecreamServer can be embedded to have forward compatible implementations.
type UnimplementedIcecreamServer struct {
}

func (*UnimplementedIcecreamServer) MoveUp(context.Context, *MoveUpReq) (*MoveUpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveUp not implemented")
}
func (*UnimplementedIcecreamServer) MoveDown(context.Context, *MoveDownReq) (*MoveDownRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveDown not implemented")
}
func (*UnimplementedIcecreamServer) MoveLeft(context.Context, *MoveLeftReq) (*MoveLeftRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveLeft not implemented")
}
func (*UnimplementedIcecreamServer) MoveRight(context.Context, *MoveRightReq) (*MoveRightRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveRight not implemented")
}
func (*UnimplementedIcecreamServer) Build(context.Context, *BuildReq) (*BuildRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (*UnimplementedIcecreamServer) VisibilityUpdates(*VisibilityUpdatesReq, Icecream_VisibilityUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method VisibilityUpdates not implemented")
}
func (*UnimplementedIcecreamServer) ChatUpdates(*ChatUpdatesReq, Icecream_ChatUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatUpdates not implemented")
}
func (*UnimplementedIcecreamServer) Say(context.Context, *SayReq) (*SayRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedIcecreamServer) Join(context.Context, *JoinReq) (*JoinRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterIcecreamServer(s *grpc.Server, srv IcecreamServer) {
	s.RegisterService(&_Icecream_serviceDesc, srv)
}

func _Icecream_MoveUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).MoveUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/MoveUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).MoveUp(ctx, req.(*MoveUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_MoveDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDownReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).MoveDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/MoveDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).MoveDown(ctx, req.(*MoveDownReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_MoveLeft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveLeftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).MoveLeft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/MoveLeft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).MoveLeft(ctx, req.(*MoveLeftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_MoveRight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRightReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).MoveRight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/MoveRight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).MoveRight(ctx, req.(*MoveRightReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).Build(ctx, req.(*BuildReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_VisibilityUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VisibilityUpdatesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IcecreamServer).VisibilityUpdates(m, &icecreamVisibilityUpdatesServer{stream})
}

type Icecream_VisibilityUpdatesServer interface {
	Send(*VisibilityUpdatesRes) error
	grpc.ServerStream
}

type icecreamVisibilityUpdatesServer struct {
	grpc.ServerStream
}

func (x *icecreamVisibilityUpdatesServer) Send(m *VisibilityUpdatesRes) error {
	return x.ServerStream.SendMsg(m)
}

func _Icecream_ChatUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatUpdatesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IcecreamServer).ChatUpdates(m, &icecreamChatUpdatesServer{stream})
}

type Icecream_ChatUpdatesServer interface {
	Send(*ChatUpdatesRes) error
	grpc.ServerStream
}

type icecreamChatUpdatesServer struct {
	grpc.ServerStream
}

func (x *icecreamChatUpdatesServer) Send(m *ChatUpdatesRes) error {
	return x.ServerStream.SendMsg(m)
}

func _Icecream_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).Say(ctx, req.(*SayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Icecream_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcecreamServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Icecream/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcecreamServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Icecream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Icecream",
	HandlerType: (*IcecreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MoveUp",
			Handler:    _Icecream_MoveUp_Handler,
		},
		{
			MethodName: "MoveDown",
			Handler:    _Icecream_MoveDown_Handler,
		},
		{
			MethodName: "MoveLeft",
			Handler:    _Icecream_MoveLeft_Handler,
		},
		{
			MethodName: "MoveRight",
			Handler:    _Icecream_MoveRight_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Icecream_Build_Handler,
		},
		{
			MethodName: "Say",
			Handler:    _Icecream_Say_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Icecream_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VisibilityUpdates",
			Handler:       _Icecream_VisibilityUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatUpdates",
			Handler:       _Icecream_ChatUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "all.proto",
}
